execute 'apt-get update'
package 'vim'
package 'postgresql-9.4'
package 'postgresql-9.4-debversion'
package 'python-argparse' 
package 'python-debian' 
package 'python-debianbts' 
package 'python-inotifyx' 
package 'python-paste' 
package 'python-psycopg2' 
package 'python-pyramid' 
package 'python-sqlalchemy'
package 'python-subversion'
package 'python-pip' 
package 'wget'

